----------------------------------------
--- DATABASE & SCHEMA CREATION ---
----------------------------------------
CREATE OR REPLACE DATABASE ACCESS_CONTROL_DB;
CREATE OR REPLACE SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA
WITH MANAGED ACCESS;

----------------------------------------
--- CREATE ACCESS ROLES ---
----------------------------------------
USE ROLE USERADMIN;
CREATE OR REPLACE ROLE S_FULL;
CREATE OR REPLACE ROLE S_WRTIE;
CREATE OR REPLACE ROLE S_READ;
CREATE OR REPLACE ROLE D_USAGE;
CREATE OR REPLACE ROLE D_FULL;

--- MANAGE GRANTS ---
USE ROLE SYSADMIN
----------------------------------------
----- GRANT READ-ONLY FOR S_READ -----
----------------------------------------
GRANT USAGE ON DATABASE ACCESS_CONTROL_DB TO ROLE S_READ;
GRANT USAGE ON SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA IN DATABASE ACCESS_CONTROL_DB TO ROLE S_READ;
--- SCHEMA ---
GRANT SELECT, REFERENCES ON ALL FUTURE TABLES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_READ;
GRANT SELECT ON ALL FUTURE EXTERNAL TABLES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_READ;
GRANT SELECT ON ALL FUTURE VIEWS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_READ;
GRANT SELECT ON ALL FUTURE MATERIALIZED VIEWS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_READ;
GRANT USAGE ON ALL FUTURE FUNCTIONS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_READ;
GRANT USAGE ON ALL FUTURE STREAMS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_READ;
GRANT USAGE ON ALL FUTURE PROCEDURES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_READ;
GRANT USAGE ON ALL FUTURE STAGES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_READ;
GRANT USAGE ON ALL FUTURE SEQUENCES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_READ;
GRANT USAGE, READ, WRITE ON ALL FUTURE FILE FORMATS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_READ; -- READ HAS TO BE FIRST?
--- DATABASE ---
GRANT SELECT, REFERENCES ON ALL FUTURE TABLES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_READ;
GRANT SELECT ON ALL FUTURE EXTERNAL TABLES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_READ;
GRANT SELECT ON ALL FUTURE VIEWS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_READ;
GRANT SELECT ON ALL FUTURE MATERIALIZED VIEWS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_READ;
GRANT USAGE ON ALL FUTURE FUNCTIONS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_READ;
GRANT USAGE ON ALL FUTURE STREAMS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_READ;
GRANT USAGE ON ALL FUTURE PROCEDURES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_READ;
GRANT USAGE ON ALL FUTURE STAGES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_READ;
GRANT USAGE ON ALL FUTURE SEQUENCES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_READ;
GRANT USAGE, READ, WRITE ON ALL FUTURE FILE FORMATS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_READ; -- READ HAS TO BE FIRST?

----------------------------------------
----- GRANT WRITE-ONLY FOR S_WRITE -----
----------------------------------------
GRANT USAGE ON DATABASE ACCESS_CONTROL_DB TO ROLE S_WRITE;
GRANT MODIFY, MONITOR, USAGE, CREATE TABLE, CREATE EXTERNAL TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE SEQUENCE, CREATE FUNCTION, CREATE PROCEDURE, CREATE FILE FORMAT 
ON SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_WRITE;
--- SCHEMA ---
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES ON ALL FUTURE TABLES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_WRITE;
GRANT SELECT ON ALL FUTURE EXTERNAL TABLES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_WRITE;
GRANT SELECT ON ALL FUTURE VIEWS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_WRITE;
GRANT SELECT ON ALL FUTURE MATERIALIZED VIEWS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_WRITE;
GRANT SELECT ON ALL FUTURE STREAMS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_WRITE;
GRANT USAGE ON ALL FUTURE FUNCTIONS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_WRITE;
GRANT USAGE ON ALL FUTURE PROCEDURES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_WRITE;
GRANT USAGE ON ALL FUTURE FILE FORMATS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_WRITE;
GRANT USAGE ON ALL FUTURE SEQUENCES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_WRITE;
GRANT USAGE, READ, WRITE ON ALL FUTURE STAGES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_WRITE; -- READ HAS TO BE FIRST?
--- DATABASE ---
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES ON ALL FUTURE TABLES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_WRITE;
GRANT SELECT ON ALL FUTURE EXTERNAL TABLES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_WRITE;
GRANT SELECT ON ALL FUTURE VIEWS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_WRITE;
GRANT SELECT ON ALL FUTURE MATERIALIZED VIEWS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_WRITE;
GRANT SELECT ON ALL FUTURE STREAMS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_WRITE;
GRANT USAGE ON ALL FUTURE FUNCTIONS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_WRITE;
GRANT USAGE ON ALL FUTURE PROCEDURES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_WRITE;
GRANT USAGE ON ALL FUTURE FILE FORMATS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_WRITE;
GRANT USAGE ON ALL FUTURE SEQUENCES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_WRITE;
GRANT USAGE, READ, WRITE ON ALL FUTURE STAGES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_WRITE; -- READ HAS TO BE FIRST?

----------------------------------------
----- GRANT READ-WRITE FOR S_FULL -----
----------------------------------------
GRANT USAGE ON DATABASE ACCESS_CONTROL_DB TO ROLE S_FULL;
GRANT MODIFY, MONITOR, USAGE, CREATE TABLE, CREATE EXTERNAL TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE SEQUENCE, CREATE FUNCTION, CREATE PROCEDURE, CREATE FILE FORMAT 
ON SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_FULL;
--- SCHEMA ---
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES ON ALL FUTURE TABLES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_FULL;
GRANT SELECT ON ALL FUTURE EXTERNAL TABLES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_FULL;
GRANT SELECT ON ALL FUTURE VIEWS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_FULL;
GRANT SELECT ON ALL FUTURE MATERIALIZED VIEWS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_FULL;
GRANT SELECT ON ALL FUTURE STREAMS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_FULL;
GRANT USAGE ON ALL FUTURE FUNCTIONS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_FULL;
GRANT USAGE ON ALL FUTURE PROCEDURES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_FULL;
GRANT USAGE ON ALL FUTURE FILE FORMATS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_FULL;
GRANT USAGE ON ALL FUTURE SEQUENCES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_FULL;
GRANT USAGE, READ, WRITE ON ALL FUTURE STAGES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_FULL; -- READ HAS TO BE FIRST?
--- DATABASE ---
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES ON ALL FUTURE TABLES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_FULL;
GRANT SELECT ON ALL FUTURE EXTERNAL TABLES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_FULL;
GRANT SELECT ON ALL FUTURE VIEWS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_FULL;
GRANT SELECT ON ALL FUTURE MATERIALIZED VIEWS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_FULL;
GRANT SELECT ON ALL FUTURE STREAMS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_FULL;
GRANT USAGE ON ALL FUTURE FUNCTIONS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_FULL;
GRANT USAGE ON ALL FUTURE PROCEDURES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_FULL;
GRANT USAGE ON ALL FUTURE FILE FORMATS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_FULL;
GRANT USAGE ON ALL FUTURE SEQUENCES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_FULL;
GRANT USAGE, READ, WRITE ON ALL FUTURE STAGES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_FULL; -- READ HAS TO BE FIRST?

----------------------------------------
----- GRANT USAGE-ONLY FOR D_USAGE -----
----------------------------------------
GRANT USAGE ON DATABASE ACCESS_CONTROL_DB TO ROLE D_USAGE;

----------------------------------------------
----- D_FULL GRANT READ-WRITE FOR D_FULL -----
----------------------------------------------
GRANT USAGE, MODIFY, MONITOR, CREATE SCHEMA ON DATABASE ACCESS_CONTROL_DB TO ROLE D_FULL;

----------------------------------------
--- ROLE HIERARCHY ---
----------------------------------------
GRANT ROLE S_FULL TO ROLE D_FULL;
GRANT ROLE S_FULL TO ROLE SYSADMIN;
GRANT ROLE S_READ TO ROLE SYSADMIN;
GRANT ROLE S_WRITE TO ROLE SYSADMIN;
GRANT ROLE D_FULL TO ROLE SYSADMIN;
GRANT ROLE D_USAGE TO ROLE SYSADMIN;

----------------------------------------
--- CREATE LOCAL ADMIN ROLE ---
----------------------------------------
CREATE OR REPLACE ROLE LOCAL_ADMIN_ROLE;
GRANT ROLE D_FULL TO ROLE LOCAL_ADMIN_ROLE;
GRANT ROLE LOCAL_ADMIN_ROLE TO ROLE SYSADMIN;



--- CREATE ADMIN USER ---

--- CREATE FUNCTIONAL ROLES ---

--- CREATE DEVELOPER USER ---

--- CREATE TABLE ---