----------------------------------------
--- DATABASE & SCHEMA CREATION ---
----------------------------------------
CREATE OR REPLACE DATABASE ACCESS_CONTROL_DB;
CREATE OR REPLACE SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA
WITH MANAGED ACCESS;

----------------------------------------
--- CREATE ACCESS ROLES ---
----------------------------------------
USE ROLE USERADMIN;
USE DATABASE ACCESS_CONTROL_DB;
CREATE OR REPLACE ROLE S_FULL;
CREATE OR REPLACE ROLE S_WRITE;
CREATE OR REPLACE ROLE S_READ;
CREATE OR REPLACE ROLE D_USAGE;
CREATE OR REPLACE ROLE D_FULL;

--- MANAGE GRANTS ---
USE ROLE SECURITYADMIN;
----------------------------------------
----- GRANT READ-ONLY FOR S_READ -----
----------------------------------------
GRANT USAGE ON DATABASE ACCESS_CONTROL_DB TO ROLE S_READ;
GRANT USAGE ON SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_READ;
--- SCHEMA ---
GRANT SELECT, REFERENCES ON FUTURE TABLES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_READ;
GRANT SELECT ON FUTURE EXTERNAL TABLES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_READ;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_READ;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_READ;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_READ;
-- GRANT USAGE ON FUTURE STREAMS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_READ; --- DOESNT
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_READ;
GRANT USAGE ON FUTURE STAGES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_READ;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_READ;
-- GRANT USAGE, READ, WRITE ON FUTURE FILE FORMATS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_READ; -- READ HAS TO BE FIRST?
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_READ;
--- DATABASE ---
GRANT SELECT, REFERENCES ON FUTURE TABLES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_READ;
GRANT SELECT ON FUTURE EXTERNAL TABLES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_READ;
GRANT SELECT ON FUTURE VIEWS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_READ;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_READ;
GRANT USAGE ON FUTURE FUNCTIONS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_READ;
-- GRANT USAGE ON FUTURE STREAMS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_READ;
GRANT USAGE ON FUTURE PROCEDURES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_READ;
GRANT USAGE ON FUTURE STAGES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_READ;
GRANT USAGE ON FUTURE SEQUENCES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_READ;
-- GRANT USAGE, READ, WRITE ON FUTURE FILE FORMATS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_READ; -- READ HAS TO BE FIRST?
GRANT USAGE ON FUTURE FILE FORMATS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_READ;

----------------------------------------
----- GRANT WRITE-ONLY FOR S_WRITE -----
----------------------------------------
GRANT USAGE ON DATABASE ACCESS_CONTROL_DB TO ROLE S_WRITE;
GRANT MODIFY, MONITOR, USAGE, CREATE TABLE, CREATE EXTERNAL TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE SEQUENCE, CREATE FUNCTION, CREATE PROCEDURE, CREATE FILE FORMAT 
ON SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_WRITE;
--- SCHEMA ---
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES ON FUTURE TABLES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_WRITE;
GRANT SELECT ON FUTURE EXTERNAL TABLES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_WRITE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_WRITE;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_WRITE;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_WRITE;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_WRITE;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_WRITE;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_WRITE;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_WRITE;
GRANT USAGE, READ, WRITE ON FUTURE STAGES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_WRITE;
--- DATABASE ---
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES ON FUTURE TABLES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_WRITE;
GRANT SELECT ON FUTURE EXTERNAL TABLES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_WRITE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_WRITE;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_WRITE;
GRANT SELECT ON FUTURE STREAMS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_WRITE;
GRANT USAGE ON FUTURE FUNCTIONS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_WRITE;
GRANT USAGE ON FUTURE PROCEDURES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_WRITE;
GRANT USAGE ON FUTURE FILE FORMATS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_WRITE;
GRANT USAGE ON FUTURE SEQUENCES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_WRITE;
GRANT USAGE, READ, WRITE ON FUTURE STAGES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_WRITE;

----------------------------------------
----- GRANT READ-WRITE FOR S_FULL -----
----------------------------------------
GRANT USAGE ON DATABASE ACCESS_CONTROL_DB TO ROLE S_FULL;
GRANT MODIFY, MONITOR, USAGE, CREATE TABLE, CREATE EXTERNAL TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE SEQUENCE, CREATE FUNCTION, CREATE PROCEDURE, CREATE FILE FORMAT 
ON SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_FULL;
--- SCHEMA ---
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES ON FUTURE TABLES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_FULL;
GRANT SELECT ON FUTURE EXTERNAL TABLES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_FULL;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_FULL;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_FULL;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_FULL;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_FULL;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_FULL;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_FULL;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_FULL;
GRANT USAGE, READ, WRITE ON FUTURE STAGES IN SCHEMA ACCESS_CONTROL_DB.MANAGED_SCHEMA TO ROLE S_FULL;
--- DATABASE ---
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES ON FUTURE TABLES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_FULL;
GRANT SELECT ON FUTURE EXTERNAL TABLES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_FULL;
GRANT SELECT ON FUTURE VIEWS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_FULL;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_FULL;
GRANT SELECT ON FUTURE STREAMS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_FULL;
GRANT USAGE ON FUTURE FUNCTIONS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_FULL;
GRANT USAGE ON FUTURE PROCEDURES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_FULL;
GRANT USAGE ON FUTURE FILE FORMATS IN DATABASE ACCESS_CONTROL_DB TO ROLE S_FULL;
GRANT USAGE ON FUTURE SEQUENCES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_FULL;
GRANT USAGE, READ, WRITE ON FUTURE STAGES IN DATABASE ACCESS_CONTROL_DB TO ROLE S_FULL;

----------------------------------------
----- GRANT USAGE-ONLY FOR D_USAGE -----
----------------------------------------
GRANT USAGE ON DATABASE ACCESS_CONTROL_DB TO ROLE D_USAGE;

----------------------------------------------
----- D_FULL GRANT READ-WRITE FOR D_FULL -----
----------------------------------------------
GRANT USAGE, MODIFY, MONITOR, CREATE SCHEMA ON DATABASE ACCESS_CONTROL_DB TO ROLE D_FULL;

----------------------------------------
--- ROLE HIERARCHY ---
----------------------------------------
GRANT ROLE S_FULL TO ROLE D_FULL;
GRANT ROLE S_FULL TO ROLE SYSADMIN;
GRANT ROLE S_READ TO ROLE SYSADMIN;
GRANT ROLE S_WRITE TO ROLE SYSADMIN;
GRANT ROLE D_FULL TO ROLE SYSADMIN;
GRANT ROLE D_USAGE TO ROLE SYSADMIN;

----------------------------------------
--- CREATE LOCAL ADMIN ROLE ---
----------------------------------------
CREATE OR REPLACE ROLE LOCAL_ADMIN_ROLE;
USE ROLE ACCOUNTADMIN;
GRANT CREATE USER, CREATE ROLE ON ACCOUNT TO ROLE LOCAL_ADMIN_ROLE WITH GRANT OPTION;
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE LOCAL_ADMIN_ROLE WITH GRANT OPTION;
USE ROLE SECURITYADMIN;
GRANT ROLE D_FULL TO ROLE LOCAL_ADMIN_ROLE;
GRANT ROLE LOCAL_ADMIN_ROLE TO ROLE SYSADMIN;


----------------------------------------
--- CREATE ADMIN USER ---
----------------------------------------
CREATE OR REPLACE USER LOCAL_ADMIN PASSWORD = 'admin' LOGIN_NAME = 'admin'
DEFAULT_ROLE='LOCAL_ADMIN_ROLE'
MUST_CHANGE_PASSWORD=FALSE;
GRANT ROLE LOCAL_ADMIN_ROLE TO USER LOCAL_ADMIN;

----------------------------------------
--- CREATE FUNCTIONAL ROLES ---
----------------------------------------
USE ROLE LOCAL_ADMIN_ROLE;
----- CREATE DEVELOPER_ROLE -----
DROP ROLE DEVELOPER_ROLE;
CREATE OR REPLACE ROLE DEVELOPER_ROLE;
GRANT ROLE D_USAGE TO ROLE DEVELOPER_ROLE;
GRANT ROLE S_WRITE TO ROLE DEVELOPER_ROLE;
GRANT ROLE DEVELOPER_ROLE TO ROLE LOCAL_ADMIN_ROLE;


----- CREATE ANALYST_ROLE -----
DROP ROLE ANALYST_ROLE;
CREATE OR REPLACE ROLE ANALYST_ROLE;
GRANT ROLE D_USAGE TO ROLE ANALYST_ROLE;
GRANT ROLE S_READ TO ROLE ANALYST_ROLE;
GRANT ROLE ANALYST_ROLE TO ROLE LOCAL_ADMIN_ROLE;

----------------------------------------
--- CREATE DEVELOPER USER ---
----------------------------------------
DROP USER DEVELOPER;
CREATE OR REPLACE USER DEVELOPER PASSWORD = 'dev' LOGIN_NAME = 'dev'
DEFAULT_ROLE='DEVELOPER_ROLE'
MUST_CHANGE_PASSWORD=FALSE;
GRANT ROLE DEVELOPER_ROLE TO USER DEVELOPER;

----------------------------------------
--- CREATE TABLE ---
----------------------------------------
USE ROLE DEVELOPER_ROLE;
CREATE OR REPLACE TABLE ACCESS_CONTROL_DB.MANAGED_SCHEMA.DEV_TABLE(
    id INT
);